### ISSUE TITLE
在http下报错TypeError: crypto.subtle is undefined

### ISSUE THREAD

**Issue by xfstu** [Jiang-K-J/enlarge-file-upload#1]
大佬，在http访问的情况下报下图错误，https是正常的（在原生html中发现），这个是啥原因啊？能修复不？另外formData想增加整个文件的hash和总的分片数量还有原始文件名，可以怎么改？谢谢

![image](https://github.com/user-attachments/assets/dee5da48-4a7e-43e6-8f00-4cc29012ba13)

![image](https://github.com/user-attachments/assets/0271ecc8-53f6-4d8b-9530-075916b3ac45)

**Comment by Jiang-K-J** [comment]
噢，你这个错误是我们已知的错误，后期我们会进行修复

**Comment by Jiang-K-J** [comment]
关于你后面提到的几个问题啊，具体的例子你可以去看我们发布在npm上的案例，你看了之后应该就能够解决你的问题了。(相关链接https://www.npmjs.com/package/enlarge-file-upload，建议下载最新版本)

**Comment by Jiang-K-J** [comment]
由于现在还在报错，是因为我们默认会自动帮你进行文件hash值的计算，但是因为你的浏览器不支持这个的API，所以你可以使用hash:false关闭掉自动计算hash值，这样它就不会报错了(其实这个参数在npm官网上的那个案例也有说的，另外建议你下载最新的版本，以避免一些其它bug)

**Comment by Jiang-K-J** [comment]
bug已经修复，请下载最新版本
